%YAML:1.0

#common parameters
imu: 1
num_of_cam: 2

imu_topic: "/imu_data"
image0_topic: "/cam00/image_raw"
image1_topic: "/cam01/image_raw"
output_path: "/home/lzzhao/catkin_output/VINS-Fusion_StereoInertial/09"

cam0_calib: "cam_09_30.yaml"
cam1_calib: "cam_09_30.yaml"
image_width: 1226
image_height: 370

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d 
   # T_cam_to_imu
   data: [ 0.0087511861, -0.0047961109,  0.9999501783,  1.1022430484,
        -0.9998642288, -0.0140024663,  0.0086832454, -0.3190719593,
         0.0139601509, -0.9998904301, -0.0049179702,  0.7460659045,
         0.0000000000,  0.0000000000,  0.0000000000,  1.0000000000]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   # T_cam1_to_imu
   data: [ 0.0087511861, -0.0047961109,  0.9999501783,  1.10694381,
        -0.9998642288, -0.0140024663,  0.0086832454, -0.8561497,
         0.0139601509, -0.9998904301, -0.0049179702,  0.75356458,
         0.0000000000,  0.0000000000,  0.0000000000,  1.0000000000]

#Multiple thread support
multiple_thread: 0

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.08  # max solver itration time (s), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 15 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.0e-3          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 1.6968e-4         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 5.0e-3         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.003491       # gyroscope bias random work noise standard deviation.     #4.0e-5
# Mathematica: GeogravityModelData[Entity["City", {"Karlsruhe", "BadenWurttemberg", "Germany"}]]
g_norm: 9.80987     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

